services:
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_DOMAIN: localhost
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    labels:
      - "com.docker.compose.project=fileserverproject"
      - "com.docker.compose.service=minio"

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - MINIO_ENDPOINT=minio:9000
      - EXTERNAL_MINIO_ENDPOINT=localhost:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_SECURE=false
      - DATABASE_PATH=/app/data/files.db
    volumes:
      - sqlite_data:/app/data
    depends_on:
      - minio
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    labels:
      - "com.docker.compose.project=fileserverproject"
      - "com.docker.compose.service=backend"

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    labels:
      - "com.docker.compose.project=fileserverproject"
      - "com.docker.compose.service=frontend"

volumes:
  minio_data:
    labels:
      - "com.docker.compose.project=fileserverproject"
  sqlite_data:
    labels:
      - "com.docker.compose.project=fileserverproject" 